# PROJECT-2[Intermediate Level]: **STOCK MARKET PRICE PREDICTION**

### Import packages

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

### Loading the datasets

In [ ]:
train_data = pd.read_csv('/content/drive/MyDrive/Labs/DI_lab/dataset_train_validation(P2-L2).csv')
train_data

,company,age,market,year,month,day,hour,minute,volume,high,...,AVERAGE_SMA_50_HIGHLOW,EMA_50_HIGHLOW,MACD_50_HIGHLOW,AVERAGE_SMA_50_VOLUME,EMA_50_VOLUME,MACD_50_VOLUME,DAYS_UNTIL_END_OF_MONTH,DAYS_UNTIL_END_OF_TRIMESTER,DINAMIC3,TARGET
0,ABEO,0.0,NASDAQ,2021,12,10,15,30,278351,0.6348,...,0.1,60000.0,20000.0,885269.5,5.061970e+08,9.576243e+08,18.0,18.0,0.2421,NaN
1,ABEO,1.0,NASDAQ,2021,12,9,15,30,617597,0.6800,...,0.1,60000.0,20000.0,887668.9,-1.389370e+09,-1.990617e+09,18.0,18.0,0.5423,NaN
2,ABEO,2.0,NASDAQ,2021,12,8,15,30,559104,662.0000,...,0.1,60000.0,20000.0,890856.3,1.798030e+09,-2.015143e+09,18.0,18.0,0.4533,NaN
3,ABEO,3.0,NASDAQ,2021,12,7,15,30,903964,648.0000,...,0.1,60000.0,20000.0,887078.7,-1.979490e+09,-5.506743e+08,18.0,18.0,0.7181,NaN
4,ABEO,4.0,NASDAQ,2021,12,6,15,30,767570,593.0000,...,0.1,60000.0,20000.0,884102.2,-6.610230e+08,-8.766870e+08,18.0,18.0,0.5691,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100039,CNCE,247.0,NASDAQ,2020,12,17,15,30,174404,13.2100,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,18.0,1.0000,NaN
100040,CNCE,248.0,NASDAQ,2020,12,16,15,30,169781,13.4000,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,18.0,1.0000,NaN
100041,CNCE,249.0,NASDAQ,2020,12,15,15,30,143397,12.9300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100042,CNCE,250.0,NASDAQ,2020,12,14,15,30,185979,13.3900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100043,CNCE,251.0,NASDAQ,2020,12,11,15,30,297530,13.5000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
test_data = pd.read_csv('/content/drive/MyDrive/Labs/DI_lab/dataset_test(P2-L2).csv')
test_data

,company,age,market,year,month,day,hour,minute,volume,high,...,AVERAGE_SMA_50_HIGHLOW,EMA_50_HIGHLOW,MACD_50_HIGHLOW,AVERAGE_SMA_50_VOLUME,EMA_50_VOLUME,MACD_50_VOLUME,DAYS_UNTIL_END_OF_MONTH,DAYS_UNTIL_END_OF_TRIMESTER,DINAMIC3,TARGET
0,CNDT,0.0,NASDAQ,2021,12,10,15,30,792397,5.41,...,0.2,230000.0,-30000.0,1173839.5,1.313408e+09,-2.066295e+09,18.0,18.0,0.5781,NaN
1,CNDT,1.0,NASDAQ,2021,12,9,15,30,1134639,5.46,...,0.2,230000.0,-20000.0,1205795.2,-1.090610e+09,-4.850086e+07,18.0,18.0,0.8089,NaN
2,CNDT,2.0,NASDAQ,2021,12,8,15,30,939646,5.47,...,0.2,230000.0,-30000.0,1201770.2,-8.206629e+08,-1.021058e+09,18.0,18.0,0.6823,NaN
3,CNDT,3.0,NASDAQ,2021,12,7,15,30,1301257,5.51,...,0.2,230000.0,-30000.0,1197837.6,-4.582356e+08,1.865824e+09,18.0,18.0,0.9432,NaN
4,CNDT,4.0,NASDAQ,2021,12,6,15,30,1090706,5365.00,...,0.2,230000.0,-30000.0,1189088.3,-6.176610e+08,-1.852724e+09,18.0,18.0,0.7731,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98187,GRTS,247.0,NASDAQ,2020,12,17,15,30,254495,3.13,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,18.0,1.0000,NaN
98188,GRTS,248.0,NASDAQ,2020,12,16,15,30,224254,3.13,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,18.0,1.0000,NaN
98189,GRTS,249.0,NASDAQ,2020,12,15,15,30,197952,3.12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98190,GRTS,250.0,NASDAQ,2020,12,14,15,30,261543,3.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98191,GRTS,251.0,NASDAQ,2020,12,11,15,30,245831,3.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Finding & replacing the *null values*

In [ ]:
print(train_data.isnull().sum())
print(test_data.isnull().sum())

company                            0
age                                0
market                             0
year                               0
month                              0
                               ...
MACD_50_VOLUME                 19850
DAYS_UNTIL_END_OF_MONTH         1191
DAYS_UNTIL_END_OF_TRIMESTER     1191
DINAMIC3                        1191
TARGET                         16277
Length: 77, dtype: int64
company                            0
age                                0
market                             0
year                               0
month                              0
                               ...
MACD_50_VOLUME                 19500
DAYS_UNTIL_END_OF_MONTH         1170
DAYS_UNTIL_END_OF_TRIMESTER     1170
DINAMIC3                        1170
TARGET                         15990
Length: 77, dtype: int64

In [ ]:
train_data.fillna(method='ffill', inplace=True)
test_data.fillna(method='ffill', inplace=True)

### Merging the datasets

In [ ]:
stockprice_data = pd.concat([train_data, test_data], axis=0)
stockprice_data

,company,age,market,year,month,day,hour,minute,volume,high,...,AVERAGE_SMA_50_HIGHLOW,EMA_50_HIGHLOW,MACD_50_HIGHLOW,AVERAGE_SMA_50_VOLUME,EMA_50_VOLUME,MACD_50_VOLUME,DAYS_UNTIL_END_OF_MONTH,DAYS_UNTIL_END_OF_TRIMESTER,DINAMIC3,TARGET
0,ABEO,0.0,NASDAQ,2021,12,10,15,30,278351,0.6348,...,0.1,60000.0,20000.0,885269.5,5.061970e+08,9.576243e+08,18.0,18.0,0.2421,NaN
1,ABEO,1.0,NASDAQ,2021,12,9,15,30,617597,0.6800,...,0.1,60000.0,20000.0,887668.9,-1.389370e+09,-1.990617e+09,18.0,18.0,0.5423,NaN
2,ABEO,2.0,NASDAQ,2021,12,8,15,30,559104,662.0000,...,0.1,60000.0,20000.0,890856.3,1.798030e+09,-2.015143e+09,18.0,18.0,0.4533,NaN
3,ABEO,3.0,NASDAQ,2021,12,7,15,30,903964,648.0000,...,0.1,60000.0,20000.0,887078.7,-1.979490e+09,-5.506743e+08,18.0,18.0,0.7181,NaN
4,ABEO,4.0,NASDAQ,2021,12,6,15,30,767570,593.0000,...,0.1,60000.0,20000.0,884102.2,-6.610230e+08,-8.766870e+08,18.0,18.0,0.5691,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98187,GRTS,247.0,NASDAQ,2020,12,17,15,30,254495,3.1300,...,1.9,1870000.0,-920000.0,3860351.3,-8.243391e+08,-1.516424e+09,18.0,18.0,1.0000,1.0
98188,GRTS,248.0,NASDAQ,2020,12,16,15,30,224254,3.1300,...,1.9,1870000.0,-920000.0,3860351.3,-8.243391e+08,-1.516424e+09,18.0,18.0,1.0000,1.0
98189,GRTS,249.0,NASDAQ,2020,12,15,15,30,197952,3.1200,...,1.9,1870000.0,-920000.0,3860351.3,-8.243391e+08,-1.516424e+09,18.0,18.0,1.0000,1.0
98190,GRTS,250.0,NASDAQ,2020,12,14,15,30,261543,3.1500,...,1.9,1870000.0,-920000.0,3860351.3,-8.243391e+08,-1.516424e+09,18.0,18.0,1.0000,1.0
98191,GRTS,251.0,NASDAQ,2020,12,11,15,30,245831,3.0400,...,1.9,1870000.0,-920000.0,3860351.3,-8.243391e+08,-1.516424e+09,18.0,18.0,1.0000,1.0

### Properties of Stockprice dataset

In [ ]:
stockprice_data.keys()

Index(['company', 'age', 'market', 'year', 'month', 'day', 'hour', 'minute',
       'volume', 'high', 'low', 'close', 'open', 'AVERAGE_SMA_3_CLOSE',
       'EMA_3_CLOSE', 'MACD_3_CLOSE', 'AVERAGE_SMA_3_OPENHIGH',
       'EMA_3_OPENHIGH', 'MACD_3_OPENHIGH', 'AVERAGE_SMA_3_HIGHLOW',
       'EMA_3_HIGHLOW', 'MACD_3_HIGHLOW', 'AVERAGE_SMA_3_VOLUME',
       'EMA_3_VOLUME', 'MACD_3_VOLUME', 'AVERAGE_SMA_4_CLOSE', 'EMA_4_CLOSE',
       'MACD_4_CLOSE', 'AVERAGE_SMA_4_OPENHIGH', 'EMA_4_OPENHIGH',
       'MACD_4_OPENHIGH', 'AVERAGE_SMA_4_HIGHLOW', 'EMA_4_HIGHLOW',
       'MACD_4_HIGHLOW', 'AVERAGE_SMA_4_VOLUME', 'EMA_4_VOLUME',
       'MACD_4_VOLUME', 'AVERAGE_SMA_7_CLOSE', 'EMA_7_CLOSE', 'MACD_7_CLOSE',
       'AVERAGE_SMA_7_OPENHIGH', 'EMA_7_OPENHIGH', 'MACD_7_OPENHIGH',
       'AVERAGE_SMA_7_HIGHLOW', 'EMA_7_HIGHLOW', 'MACD_7_HIGHLOW',
       'AVERAGE_SMA_7_VOLUME', 'EMA_7_VOLUME', 'MACD_7_VOLUME',
       'AVERAGE_SMA_20_CLOSE', 'EMA_20_CLOSE', 'MACD_20_CLOSE',
       'AVERAGE_SMA_20_OPENHIGH', 'EMA_20_OPENHIGH', 'MACD_20_OPENHIGH',
       'AVERAGE_SMA_20_HIGHLOW', 'EMA_20_HIGHLOW', 'MACD_20_HIGHLOW',
       'AVERAGE_SMA_20_VOLUME', 'EMA_20_VOLUME', 'MACD_20_VOLUME',
       'AVERAGE_SMA_50_CLOSE', 'EMA_50_CLOSE', 'MACD_50_CLOSE',
       'AVERAGE_SMA_50_OPENHIGH', 'EMA_50_OPENHIGH', 'MACD_50_OPENHIGH',
       'AVERAGE_SMA_50_HIGHLOW', 'EMA_50_HIGHLOW', 'MACD_50_HIGHLOW',
       'AVERAGE_SMA_50_VOLUME', 'EMA_50_VOLUME', 'MACD_50_VOLUME',
       'DAYS_UNTIL_END_OF_MONTH', 'DAYS_UNTIL_END_OF_TRIMESTER', 'DINAMIC3',
       'TARGET'],
      dtype='object')

In [ ]:
print("The dimension:", stockprice_data.shape)

The dimension: (198236, 77)

In [ ]:
print(stockprice_data.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 198236 entries, 0 to 98191
Data columns (total 77 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   company                      198236 non-null  object
 1   age                          198236 non-null  float64
 2   market                       198236 non-null  object
 3   year                         198236 non-null  int64
 4   month                        198236 non-null  int64
 5   day                          198236 non-null  int64
 6   hour                         198236 non-null  int64
 7   minute                       198236 non-null  int64
 8   volume                       198236 non-null  int64
 9   high                         198236 non-null  float64
 10  low                          198236 non-null  float64
 11  close                        198236 non-null  float64
 12  open                         198236 non-null  float64
 13  AVERAGE_SMA_3_CLOSE          198236 non-null  float64
 14  EMA_3_CLOSE                  198236 non-null  float64
 15  MACD_3_CLOSE                 198236 non-null  float64
 16  AVERAGE_SMA_3_OPENHIGH       198236 non-null  float64
 17  EMA_3_OPENHIGH               198236 non-null  float64
 18  MACD_3_OPENHIGH              198236 non-null  float64
 19  AVERAGE_SMA_3_HIGHLOW        198236 non-null  float64
 20  EMA_3_HIGHLOW                198236 non-null  float64
 21  MACD_3_HIGHLOW               198236 non-null  float64
 22  AVERAGE_SMA_3_VOLUME         198236 non-null  float64
 23  EMA_3_VOLUME                 198236 non-null  float64
 24  MACD_3_VOLUME                198236 non-null  float64
 25  AVERAGE_SMA_4_CLOSE          198236 non-null  float64
 26  EMA_4_CLOSE                  198236 non-null  float64
 27  MACD_4_CLOSE                 198236 non-null  float64
 28  AVERAGE_SMA_4_OPENHIGH       198236 non-null  float64
 29  EMA_4_OPENHIGH               198236 non-null  float64
 30  MACD_4_OPENHIGH              198236 non-null  float64
 31  AVERAGE_SMA_4_HIGHLOW        198236 non-null  float64
 32  EMA_4_HIGHLOW                198236 non-null  float64
 33  MACD_4_HIGHLOW               198236 non-null  float64
 34  AVERAGE_SMA_4_VOLUME         198236 non-null  float64
 35  EMA_4_VOLUME                 198236 non-null  float64
 36  MACD_4_VOLUME                198236 non-null  float64
 37  AVERAGE_SMA_7_CLOSE          198236 non-null  float64
 38  EMA_7_CLOSE                  198236 non-null  float64
 39  MACD_7_CLOSE                 198236 non-null  float64
 40  AVERAGE_SMA_7_OPENHIGH       198236 non-null  float64
 41  EMA_7_OPENHIGH               198236 non-null  float64
 42  MACD_7_OPENHIGH              198236 non-null  float64
 43  AVERAGE_SMA_7_HIGHLOW        198236 non-null  float64
 44  EMA_7_HIGHLOW                198236 non-null  float64
 45  MACD_7_HIGHLOW               198236 non-null  float64
 46  AVERAGE_SMA_7_VOLUME         198236 non-null  float64
 47  EMA_7_VOLUME                 198236 non-null  float64
 48  MACD_7_VOLUME                198236 non-null  float64
 49  AVERAGE_SMA_20_CLOSE         198236 non-null  float64
 50  EMA_20_CLOSE                 198236 non-null  float64
 51  MACD_20_CLOSE                198236 non-null  float64
 52  AVERAGE_SMA_20_OPENHIGH      198236 non-null  float64
 53  EMA_20_OPENHIGH              198236 non-null  float64
 54  MACD_20_OPENHIGH             198236 non-null  float64
 55  AVERAGE_SMA_20_HIGHLOW       198236 non-null  float64
 56  EMA_20_HIGHLOW               198236 non-null  float64
 57  MACD_20_HIGHLOW              198236 non-null  float64
 58  AVERAGE_SMA_20_VOLUME        198236 non-null  float64
 59  EMA_20_VOLUME                198236 non-null  float64
 60  MACD_20_VOLUME               198236 non-null  float64
 61  AVERAGE_SMA_50_CLOSE         198236 non-null  float64
 62  EMA_50_CLOSE                 198236 non-null  float64
 63  MACD_50_CLOSE                198236 non-null  float64
 64  AVERAGE_SMA_50_OPENHIGH      198236 non-null  float64
 65  EMA_50_OPENHIGH              198236 non-null  float64
 66  MACD_50_OPENHIGH             198236 non-null  float64
 67  AVERAGE_SMA_50_HIGHLOW       198236 non-null  float64
 68  EMA_50_HIGHLOW               198236 non-null  float64
 69  MACD_50_HIGHLOW              198236 non-null  float64
 70  AVERAGE_SMA_50_VOLUME        198236 non-null  float64
 71  EMA_50_VOLUME                198236 non-null  float64
 72  MACD_50_VOLUME               198236 non-null  float64
 73  DAYS_UNTIL_END_OF_MONTH      198236 non-null  float64
 74  DAYS_UNTIL_END_OF_TRIMESTER  198236 non-null  float64
 75  DINAMIC3                     198236 non-null  float64
 76  TARGET                       198194 non-null  float64
dtypes: float64(69), int64(6), object(2)
memory usage: 118.0+ MB
None

In [ ]:
print(stockprice_data.describe())

                 age           year          month            day  \
count  198236.000000  198236.000000  198236.000000  198236.000000
mean      125.463599    2020.944490       6.584510      15.646855
std        72.739397       0.228973       3.423952       8.728768
min         0.000000    2020.000000       1.000000       1.000000
25%        62.000000    2021.000000       4.000000       8.000000
50%       125.000000    2021.000000       7.000000      16.000000
75%       188.000000    2021.000000      10.000000      23.000000
max       251.000000    2021.000000      12.000000      31.000000

                hour    minute        volume          high           low  \
count  198236.000000  198236.0  1.982360e+05  1.982360e+05  1.982360e+05
mean       14.940500      30.0  1.345943e+06  3.343477e+03  3.052673e+03
std         0.236558       0.0  7.153822e+06  3.356120e+04  2.973231e+04
min        14.000000      30.0  0.000000e+00  2.797000e-01  2.689000e-01
25%        15.000000      30.0  6.513875e+04  6.655825e+00  6.200000e+00
50%        15.000000      30.0  2.402745e+05  1.980000e+01  1.877000e+01
75%        15.000000      30.0  7.997432e+05  5.142000e+01  4.818000e+01
max        15.000000      30.0  8.054308e+08  2.925075e+06  2.944895e+06

               close  ...  AVERAGE_SMA_50_HIGHLOW  EMA_50_HIGHLOW  \
count  198236.000000  ...           198236.000000    1.982360e+05
mean      251.157445  ...                1.530589    1.530280e+06
std      4037.400661  ...                3.006941    3.006833e+06
min         0.269900  ...                0.000000    0.000000e+00
25%         6.030000  ...                0.300000    3.000000e+05
50%        17.640000  ...                0.700000    7.300000e+05
75%        41.550000  ...                1.600000    1.630000e+06
max    858105.000000  ...               56.700000    5.668000e+07

       MACD_50_HIGHLOW  AVERAGE_SMA_50_VOLUME  EMA_50_VOLUME  MACD_50_VOLUME  \
count     1.982360e+05           1.982360e+05   1.982360e+05    1.982360e+05
mean     -2.114782e+04           1.439395e+06  -8.303033e+06   -2.506850e+07
std       5.020772e+05           4.276193e+06   1.243895e+09    1.232027e+09
min      -1.173000e+07           2.194000e+02  -2.147447e+09   -2.147484e+09
25%      -7.000000e+04           9.067530e+04  -1.094379e+09   -1.078756e+09
50%       0.000000e+00           3.262031e+05  -1.013707e+07   -4.358270e+07
75%       5.000000e+04           1.020854e+06   1.068916e+09    1.040056e+09
max       1.358000e+07           1.096805e+08   2.147458e+09    2.147451e+09

       DAYS_UNTIL_END_OF_MONTH  DAYS_UNTIL_END_OF_TRIMESTER       DINAMIC3  \
count                 198236.0                     198236.0  198236.000000
mean                      18.0                         18.0      74.341128
std                        0.0                          0.0     578.854076
min                       18.0                         18.0       0.000000
25%                       18.0                         18.0       0.562600
50%                       18.0                         18.0       0.955100
75%                       18.0                         18.0       1.085700
max                       18.0                         18.0   70604.000000

              TARGET
count  198194.000000
mean        0.092657
std         0.289951
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

[8 rows x 75 columns]

### Splitting the data into *training* and *testing* sets

In [ ]:
stockprice_data = stockprice_data['close'].values.reshape(-1, 1)
scaler = MinMaxScaler(feature_range=(0, 1))
combined_data = scaler.fit_transform(stockprice_data)

In [ ]:
train_data_len = len(train_data)
train_data = stockprice_data[:train_data_len]
test_data = stockprice_data[train_data_len:]

### Training the model using the ***Random Forest model***

In [ ]:
def train_random_forest_model(train_data):
    X_train = np.arange(1, len(train_data) + 1).reshape(-1, 1)
    y_train = train_data.flatten()

    # Handle missing values in y_train
    y_train = pd.Series(y_train).fillna(pd.Series(y_train).mean()).values

    model = RandomForestRegressor(n_estimators=100)
    model.fit(X_train, y_train)

    return model

rf_model = train_random_forest_model(train_data)

### Evaluation of model predictions

In [ ]:
X_test = np.arange(train_data_len, train_data_len + len(test_data) - 1).reshape(-1, 1)
rf_predictions = rf_model.predict(X_test)

In [ ]:
y_test = scaler.inverse_transform(test_data[:-1])
y_test = y_test.flatten()

### Calculating **RMSE** for *Random Forest* model

In [ ]:
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
print("Random Forest RMSE:", rf_rmse)

Random Forest RMSE: 2742217337.247875

# **THE END**